version: '3'

services:

  mock:
      image: local/mock
      build:
        context: ../apps/suap_mock
      env_file:
        .env
      ports:
        - 7777:7777
      volumes:
        - ../apps/suap_mock:/app
        - /app/vendor