version: '3'

services:

  app:
      image: local/mock
      build:
        context: ../dockers/suap_mock
      env_file:
        .env
      ports:
        - 7777:7777
      volumes:
        - .:/app
        - /app/vendor