version: '3.0'

services:

  mockup:
    image: coticeadifrn/moodle_suap_mockup
    build:
      context: ../apps/moodle_suap_mockup
    env_file: .env
    ports:
      - 7777:7777
    volumes:
      - ../apps/moodle_suap_mockup:/app
      - /app/vendor
  
  integrador_ms:
    image: coticeadifrn/integrador_ms
    build:
      context: ../apps/moodle_suap_integrador_ms
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ../apps/moodle_suap_integrador_ms:/apps/app

  integrador_app:
    image: coticeadifrn/integrador_app
    build:
      context: ../apps/moodle_suap_integrador_app
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ../apps/moodle_suap_integrador_app:/apps/app
    depends_on:
      - mockup
      - integrador_ms